#!/usr/bin/env python3
"""
================================================================================
  IntelliBI Operations Automation — EVENING batch  (scripts/run_evening_reports.py)
  ------------------------------------------------------------------------------
  Reports that must run AFTER the working day, once the Coordinator has worked
  the morning task list:

      pyCoordinatorTaskPerformanceReport   (co-ordinator reports/)
          reads the day's Batch Coordinator task report(s) — generated by the
          Morning batch (scripts/run_all.py → run_reports_action.py) — and
          measures completion and timeliness for the planned Daily / Weekly /
          Monthly period(s).

  Same conventions as the Morning batch (scripts/run_all.py): each script runs
  through common_utils.run_script (logging, quota retry, record counts), and a
  completion e-mail with the per-script summary + logs goes to
  config.yaml email.log_recipients on every real execution.

  Scheduled by scripts/setup_schedule.ps1 at 19:00 (20:00 = retry-only window)
  through scripts/run_scheduled.py --label ops_evening --once-per-day
  --entry run_evening_reports.py.

  Run by hand:   python scripts/run_evening_reports.py
  Exit code 0 = every job succeeded, else 1.
================================================================================
"""
import os
import sys
from datetime import datetime

sys.path.insert(0, os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "common"))
import _bootstrap            # noqa: E402,F401
import paths                 # noqa: E402
import logging_utils         # noqa: E402
import common_utils          # noqa: E402
import config_loader         # noqa: E402
import exec_summary          # noqa: E402

LAYER = "Evening — Coordinator Performance"

# script stem -> display label (run in this order)
JOBS = [
    ("pyCoordinatorTaskPerformanceReport", "Coordinator Task Performance Report"),
]


def _timeout():
    t = config_loader.get("pipeline.script_timeout_seconds", "")
    try:
        return int(t) if str(t).strip() else None
    except (TypeError, ValueError):
        return None


def run(logger=None) -> dict:
    log = logger or logging_utils.get_logger("run_evening_reports")
    logging_utils.section(log, f"{LAYER}: running {len(JOBS)} job(s)")
    timeout = _timeout()
    scripts = [common_utils.run_script(paths.COORDINATOR_DIR / f"{stem}.py",
                                       label=label, timeout=timeout)
               for stem, label in JOBS]
    ok = all(r["status"] == "SUCCESS" for r in scripts)
    if not ok:
        log.error("%s: FAILED jobs -> %s", LAYER,
                  ", ".join(r["name"] for r in scripts if r["status"] != "SUCCESS"))
    return {"layer": LAYER, "ok": ok, "scripts": scripts}


def main() -> int:
    log = logging_utils.get_logger("run_evening_reports")
    started = datetime.now()
    result = run(logger=log)
    ended = datetime.now()
    overall_ok = result["ok"]
    logging_utils.section(
        log, f"EVENING BATCH {'SUCCESS' if overall_ok else 'COMPLETED WITH ISSUES'} in "
        f"{common_utils.fmt_duration((ended - started).total_seconds())}")

    # completion e-mail — identical mechanism to scripts/run_all.py
    if config_loader.get("email.send_log_summary", True):
        recipients = config_loader.get(
            "email.log_recipients", ["info@intellibiinnovationstechnologies.in"])
        if isinstance(recipients, str):
            recipients = [recipients]
        attach = []
        if config_loader.get("email.attach_layer_logs", True):
            for r in result["scripts"]:
                lf = r.get("log_file")
                if lf and os.path.exists(lf) and lf not in attach:
                    attach.append(lf)
        subject = (f"IntelliBI Operations Automation (Evening) — "
                   f"{exec_summary.pipeline_status([result])} — {ended.strftime('%d-%b-%Y %H:%M')}")
        html = common_utils.build_summary_html(
            [result], overall_ok,
            started.strftime("%Y-%m-%d %H:%M:%S"), ended.strftime("%Y-%m-%d %H:%M:%S"))
        common_utils.send_summary_email(subject, html, recipients, logger=log,
                                        attach_logs=attach)
    else:
        log.info("email.send_log_summary is false — no summary e-mail sent.")
    return 0 if overall_ok else 1


if __name__ == "__main__":
    sys.exit(main())
